# Script to process images and analyse them for apical fluid volume
# Sam Siljee
# 6th September 2024

---
title: "Apical fluid analysis"
author: "Sam Siljee"
date: '2022-09-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(dplyr) # Data manipulation
library(ggplot2) # Plotting
library(stringr) # String manipulation in annotations
library(tiff) # Read in .tiff files
library(png) # Write .png images

# Files and directories
input_dir <- paste0(getwd(), "/data/")
output_dir <- paste0(getwd(), "/results/")

# User variables
min_offset <- -90
max_offset <-5
magnification <- "4x" # "10X"
wash <- "post" # "pre wash"

# Load custom functions
source("Functions.R")
```

# Apical fluid analysis
Run main loop processing the data, iterating over each image
```{r Run processing}
# List input files filtering using the variables from setup
input_files <- list.files(input_dir) %>%
  grep(pattern = ".tif$", value = TRUE) %>%
  grep(pattern = magnification, value = TRUE) %>%
  grep(pattern = wash, value = TRUE)

# Create annotations from file names
annotations <- data.frame(file_name = input_files) %>%
  mutate(
    Donor = substr(file_name, start = 1, stop = 6),
    Well = str_extract(file_name, "(?<=well )\\d(?= )"),
    Rotation = str_extract(file_name, "(?<= wash )\\d{2,3}(?= well )"),
    ID = paste(Donor, Well, Rotation, sep = "_"),
    Condition = ifelse(Well %in% c(1, 2, 3), "Control", "p53 KD")
  )

# Read in intensity curve cutoffs
intensity_cutoffs <- read.csv(paste0(input_dir, "curve_cutoffs_", magnification, "_", wash,"_wash.csv"), header = TRUE)

# Initialise list for results
area_results <- list()

# Start loop through images
for (i in 1:nrow(annotations)) {
  # Set some variables
  file_name <- annotations$file_name[i]
  ID <- annotations$ID[i]
  
  # Get manual intensity cutoff value
  intensity_cutoff <- intensity_cutoffs[intensity_cutoffs$ID == ID, 2]
  
  # Print progress check
  print(paste0("Starting on ", ID, ", ", i, " of ", nrow(annotations)))

  # Load the image
  image_matrix <- readTIFF(paste0(input_dir, file_name), as.is = TRUE)

  # Convert to grey-scale image - sum all channels
  image_matrix <- image_matrix[, , 1] + image_matrix[, , 2] + image_matrix[, , 3]
  
  # Get number of rows for other functions
  image_height <- nrow(image_matrix)

  # Flip on vertical axis if image taken at 90 degrees position
  if (annotations$Rotation[i] == 90) {
    image_matrix <- image_matrix[, ncol(image_matrix):1]
  }

  # Run function to identify best offsets
  best_offsets <- get_alignment_offsets(image_matrix, min_offset, max_offset)
  
  # Plot best offsets
  data.frame(Row = 1:image_height, Offset = best_offsets) %>%
    ggplot(aes(x = Row, y = Offset)) +
    geom_line() +
    coord_flip() +
    labs(
      title = paste("Calcualted offset values for image ", ID),
      x = "Image row",
      y = "Row offset value"
    ) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
      legend.position = "none"
    )
  
  # Save the plot
  ggsave(paste0(output_dir, "offset_plots/", ID, "_offset_plot.png"), width = 8, height = 5.5)

  # Align rows, saving an image of the aligned matrix and make a column means vector
  aligned_matrix <- align_matrix(image_matrix, -best_offsets)
  
  # Make an image with a red line for the intensity cutoff
  aligned_image <- array(dim = c(dim(aligned_matrix), 3))
  aligned_image[,,1:3] <- normalise_image(aligned_matrix) # All three channels the same
  # Add in red line
  aligned_image[,(intensity_cutoff - 2) : (intensity_cutoff + 2),1] <- 1
  aligned_image[,(intensity_cutoff - 2) : (intensity_cutoff + 2),2:3] <- 0
  
  # Save as a PNG image - grayscale
  writePNG(aligned_image, paste0(output_dir, "aligned_images/", ID, "_aligned_image.png"))
  
  # Get intensity values
  intensity_vector <- colMeans(aligned_matrix)

  # Make a plot of the intensity values
  data.frame(Column = 1:length(intensity_vector), Intensity = intensity_vector) %>%
    ggplot(aes(x = Column, y = Intensity)) +
    geom_line() +
    geom_vline(xintercept = intensity_cutoff, col = "red") +
    labs(
      title = paste("Aligned column mean intensity:", ID),
      x = "Image column",
      y = "Mean intensity"
    ) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
      legend.position = "none"
    )
  
  # Save the plot
  ggsave(paste0(output_dir, "intensity_plots/", ID, "_intensity_plot.png"), width = 8, height = 5.5)
  
  # Trim off area corresponding to the transwell wall
  intensity_vector <- intensity_vector[intensity_cutoff:length(intensity_vector)]

  # Subtract background by using minimal intenstiy values

  # Model curve

  # calculate area under the curve
}
```
